ffmpeg -i central-and-western-district.m4a -ab 256k -acodec mp3 central-and-western-district.mp3
ffmpeg -i eastern-district.m4a -ab 256k -acodec mp3 eastern-district.mp3
ffmpeg -i islands-district.m4a -ab 256k -acodec mp3 islands-district.mp3
ffmpeg -i kowloon-city-district.m4a -ab 256k -acodec mp3 kowloon-city-district.mp3
ffmpeg -i kwai-tsing-district.m4a -ab 256k -acodec mp3 kwai-tsing-district.mp3
ffmpeg -i kwun-tong-district.m4a -ab 256k -acodec mp3 kwun-tong-district.mp3
ffmpeg -i north-district.m4a -ab 256k -acodec mp3 north-district.mp3
ffmpeg -i sai-kung-district.m4a -ab 256k -acodec mp3 sai-kung-district.mp3
ffmpeg -i sha-tin-district.m4a -ab 256k -acodec mp3 sha-tin-district.mp3
ffmpeg -i sham-shui-po-district.m4a -ab 256k -acodec mp3 sham-shui-po-district.mp3
ffmpeg -i southern-district.m4a -ab 256k -acodec mp3 southern-district.mp3
ffmpeg -i tai-po-district.m4a -ab 256k -acodec mp3 tai-po-district.mp3
ffmpeg -i tsuen-wan-district.m4a -ab 256k -acodec mp3 tsuen-wan-district.mp3
ffmpeg -i tuen-mun-district.m4a -ab 256k -acodec mp3 tuen-mun-district.mp3
ffmpeg -i wan-chai-district.m4a -ab 256k -acodec mp3 wan-chai-district.mp3
ffmpeg -i wong-tai-sin-district.m4a -ab 256k -acodec mp3 wong-tai-sin-district.mp3
ffmpeg -i yau-tsim-mong-district.m4a -ab 256k -acodec mp3 yau-tsim-mong-district.mp3
ffmpeg -i yuen-long-district.m4a -ab 256k -acodec mp3 yuen-long-district.mp3
