extends:
  - ./.eslintrc.custom.yml
ignorePatterns:
  - '**/*.d.mts'
  - '**/*.d.ts'
overrides:
  - env:
      commonjs: true
    files:
      - '**/*.js'
      - '**/*.ts'
    parserOptions:
      ecmaVersion: latest
    rules:
      import/no-commonjs: off
  - files:
      - '**/*.mjs'
      - '**/*.mts'
    parserOptions:
      ecmaVersion: latest
      sourceType: module
rules:
  import/no-mutable-exports: off
